# Generated by Django 4.0.4 on 2022-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='gamer', to='levelupapi.gamer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.TextField(),
        ),
    ]
